import { auth } from "@/auth";
import Navbar from "@/components/navbar";
import SidebarComponent from "@/components/sidebar";
import { AppProvider } from "@/context/AppProvider";
import { Metadata } from "next";
import React from "react";

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "MENTEM | Chat",
  description: "Generated by create next app",
};

const AdminLayout = async ({ children }: Props) => {
  const session = await auth();
  return (
    <AppProvider userId={session?.user.id}>
      <div className="bg-[#EAEDEF]">
        <Navbar />
        <SidebarComponent />
        <div className="sm:ps-72 w-full sm:p-2">
          <main className="pt-14 h-[calc(100vh_-_16px)] overflow-hidden rounded-sm bg-white">
            {children}
          </main>
        </div>
      </div>
    </AppProvider>
  );
};

export default AdminLayout;
